const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE : "CHANGE_LANGUAGE",
    //admin
    ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
 
    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    //fetchTopDoctorHomeSuccess
    FETCH_TOP_DOCTOR_HOME_SUCCESS:"FETCH_TOP_DOCTOR_HOME_SUCCESS",
    FETCH_TOP_DOCTOR_HOME_FAILED:"FETCH_TOP_DOCTOR_HOME_FAILED",

    FETCH_ALL_USER_SUCCESS:"FETCH_ALL_USER_SUCCESS",
    //
    SaveDetailDoctorSuccess:"saveDetailDoctorSuccess",
    SaveDetailDoctorFailed:"saveDetailDoctorFailed",
    //
    FETCH_ALLCODE_SCHEDULE_HOURS_SUCESS: "FETCH_ALLCODE_SCHEDULE_HOURS_SUCESS",
    FETCH_ALLCODE_SCHEDULE_HOURS_FAIL: "FETCH_ALLCODE_SCHEDULE_HOURS_FAIL",
    //
    
    FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFO_SUCCESS",
    FETCH_REQUIRED_DOCTOR_INFO_FAIL: "FETCH_REQUIRED_DOCTOR_INFO_FAIL"
    
})

export default actionTypes;